name: Nostale Bot Exe Derleyici

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # İstediğin zaman GitHub paneli üzerinden manuel başlatabilmek için

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Depoyu Klonla
      uses: actions/checkout@v4

    - name: Python Kur
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Gerekli Kütüphaneleri Yükle
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller ultralytics opencv-python pyautogui mss keyboard customtkinter pywin32

    - name: PyInstaller ile EXE Oluştur
      run: |
        # --onefile: Tek bir exe oluşturur
        # --noconsole: Arkadaki siyah cmd ekranını gizler, sadece CustomTkinter menüsü açılır
        # --add-data: Eğittiğin yapay zeka modelini (.pt) exe içine gömer (Windows için aralarına ; koyulur)
        pyinstaller --onefile --noconsole --add-data "olta_modeli.pt;." --name="Nostale_Yapay_Zeka_Botu" main.py

    - name: Oluşan EXE'yi Artefakt Olarak Yükle
      uses: actions/upload-artifact@v4
      with:
        name: Nostale_Yapay_Zeka_Botu_EXE
        path: dist/Nostale_Yapay_Zeka_Botu.exe
        
